[project]
name = "chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "linhengyang", email = "linhengyang1@outlook.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
chat = "chat:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
