[project]
name = "chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "linhengyang", email = "linhengyang1@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "openai>=3.19.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
chat = "chat:main"
